### ISSUE TITLE
With which version of metabase shall we test the driver ?

### ISSUE THREAD

**Issue by TH-HA** [enqueue/metabase-clickhouse-driver#1]
Hello 
First , thanks for moving forward on metabase. This is something i was looking since at least 6 months. 
Now i want to test the clickhouse drivers , but following the procedure you describe ( the simple one , get the driver prerelase and put them in the plugin directory) is not working ( the clickhouse driveris not visible when adding a database). After digging a bit , i'm under the impression that dynamic driver loading is not supported before the 3.2 of metabase ( not yet release). 

Can you confirm that and that the only way to test the new drivers is to have a dev environment where you should add the drivers as decribe in your doc ?

Thanks in advance 

ps : To increase the number of people testing the drivers and have more feedback to make it official at metabase , it can be usefull to provide a beta version of the metabase jar including the drivers ? ( Of course if the guys /license of metabase allow it)

**Comment by TH-HA** [comment]
In fact the driver are loading but with a warning and they are not accessible from the addDB panel 

Here is the log: 
03-14 11:57:48 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
03-14 11:57:48 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

03-14 11:57:48 [1mINFO metabase.core[0m :: Starting Metabase version v0.31.2 (89c37eb release-0.31.2) ...
03-14 11:57:48 [1mINFO metabase.core[0m :: System timezone is 'Europe/Paris' ...
03-14 11:57:48 [1mINFO metabase.plugins[0m :: Loading plugins in directory f:\METABASE\plugins...
03-14 11:57:48 [1mINFO metabase.plugins[0m :: Loading plugin f:\METABASE\plugins\clickhouse.metabase-driver.jar...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?

**Comment by enqueue** [comment]
Hi @TH-HA thanks for being so brave to test the driver! I have not looked into other methods of running the the MetaBase environment. There might be a good chance that you could pick up one of the Metabase Circle CI builds and then start MetaBase setting the `MB_PLUGINS_DIR` environment variable to the directory where you have placed `clickhouse.metabase-driver.jar`. Alternatively, you could use the [MetaBase Head Docker Image](https://hub.docker.com/r/metabase/metabase-head) and mount your plugins directory as volume into the container. I have no experience with this, though.

Did you download the jar from this repository's release page or did you build yourself?

**Comment by TH-HA** [comment]
I 've downloaded it from the release page. From the log we can see that the plugin dir is correct and the driver loaded. But still no DB type clickhouse. 
I don't think it's coming from the driver by themself as i've done the following test : trying the spark driver as referenced here : https://www.metabase.com/docs/v0.29.2/administration-guide/databases/spark.html and i have the same issue.

Regards

**Comment by enqueue** [comment]
MetaBase 0.32 was released recently. You can download the jar and add the driver easily. I updated the README and included the steps you'd need to take. Please report any issues. Thanks!

**Comment by TH-HA** [comment]
Thanks , it's working now. I 'll send you feedback if i face any issue. 
Thanks to you
