### ISSUE TITLE
Check Behavior for Array, Enum Data Types

### ISSUE THREAD

**Issue by enqueue** [enqueue/metabase-clickhouse-driver#10]
We should check whether the use of more complicated data types breaks the driver somehow.

Candidates:

* `Array(String)`
* `Array(Array(UInt64))`
* `Array(LowCardinality(String))`
* `Enum8('foo' = 42, 'bar' = 23)`

**Comment by nilaymk** [comment]
@enqueue I can test this bit and report back. We're using latest Metabase (0.44.x) with very recent Clickhouse, and we use all above datatypes type in our Clickhouse DB.

That said we only use  native Clickhouse SQL queries in our Metabase Questions and not the Metabase UI generated ones.

Are there particular tests that you'd like me to run?

(p.s. I don't have setup to run unit tests / integration tests etc. but I can certainly perform end-user tests)
