### ISSUE TITLE
runntime error when using metabase v0.44.3

### ISSUE THREAD

**Issue by colin-lee** [enqueue/metabase-clickhouse-driver#100]
the structure is error,

"Could not locate metabase/driver/clickhouse__init.class, metabase/driver/clickhouse.clj or metabase/driver/clickhouse.cljc on classpath."

**Comment by goFrendiAsgard** [comment]
Do you use metabase-clickhouse-driver `0.8.1`?

If you run metabase natively (i.e., using metabase.jar), you need to define `MB_PLUGINS_DIR` as well:

https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_plugins_dir
