### ISSUE TITLE
clickhouse exception read timed out

### ISSUE THREAD

**Issue by jack-reso** [enqueue/metabase-clickhouse-driver#102]
when i use sql search,it came clickhouse exception read timed out.
i think if i can change jdbc's socket_timeouttime ,it can solve.
but i can't find it in metabase.
my metabase is  v0.44.5
my clickhouse is 22.3.2
my metabase-clickhouse-driver is 0.8.1

**Comment by jack-reso** [comment]
ok,i sovle it.

**Comment by slvrtrn** [comment]
`socket_timeout` (and other JDBC options) should be available under the advanced options in the UI now (as of 0.8.3)
