### ISSUE TITLE
error timezone

### ISSUE THREAD

**Issue by jack-reso** [enqueue/metabase-clickhouse-driver#103]
**Timezone problems**

i have already change wherever timezone i can find to solve it,like in docker-compose  for metabase and postgres, set JAVA_TIMEZONE: xxx,TZ:xxx.
also clickhouse's config.xml also change to xxx.
but in metabase,when i search "select now()"  ,it's not right,it's still UTC timezone.

my metabase is v0.44.5
my clickhouse is 22.3.2
my metabase-clickhouse-driver is 0.8.1

what can i do?

**Comment by FesonX** [comment]
Same on metabase-clickhouse-driver-0.8.3

**Comment by slvrtrn** [comment]
@FesonX thanks for testing, will look into it.

**Comment by slvrtrn** [comment]
Let's keep it open until 0.9.0 release

**Comment by slvrtrn** [comment]
Should be fixed in [0.9.0](https://github.com/enqueue/metabase-clickhouse-driver/releases/tag/0.9.0)
