### ISSUE TITLE
When will a new version be available that is compatible with metabase v0.44 or higher?

### ISSUE THREAD

**Issue by yjynipyg** [enqueue/metabase-clickhouse-driver#105]
When will a new version be available that is compatible with metabase v0.44 or higher?

**Comment by slvrtrn** [comment]
Stay tuned. We are working on it :)

**Comment by enqueue** [comment]
Please try driver version 0.8.2 and report your findings.

**Comment by slvrtrn** [comment]
Feel free to re-open this issue or create a new one(s) in case of any issues with 0.8.3.
