### ISSUE TITLE
i think there is something wrong with the timezone

### ISSUE THREAD

**Issue by li-bit** [enqueue/metabase-clickhouse-driver#19]
https://discourse.metabase.com/t/problem-with-today-filter-in-dashboard/6537

**Comment by enqueue** [comment]
Hi @kkxxr66573 I would like to help you, and investigate the issue. But I need some more details for this. Please read through the [Metabase checklist](https://metabase.com/docs/latest/troubleshooting-guide/timezones.html#troubleshooting-process) and then let me know some details about

* Your environment
** What timezone do you run your ClickHouse server in?
** What timezone do you run your Metabase server in?
** What timezone does your browser run in?
** Are you using any specific JDBC driver settings?
* The "test case", i.e. your query
* The expected result
* The actual result

Thank you! Have a nice day and best regards.

**Comment by kkxxr66573** [comment]
What timezone do you run your ClickHouse server in?
-- SELECT timezone()

┌─timezone()─┐
│ ROC        │
└────────────┘

What timezone do you run your Metabase server in?
--java -Duser.timezone=Asia/Taipei -jar metabase.jar

![image](https://user-images.githubusercontent.com/13388843/62926662-84864d80-bde7-11e9-90a1-2f91426441ad.png)

**Comment by kkxxr66573** [comment]
but the datetime in clickhouse-client is diff with metabase,clickhouse-client is right

![image](https://user-images.githubusercontent.com/13388843/62926718-a2ec4900-bde7-11e9-8df5-31585563b249.png)


![image](https://user-images.githubusercontent.com/13388843/62926728-a8e22a00-bde7-11e9-98d5-2151768715c7.png)

**Comment by enqueue** [comment]
When the driver initializes the connection, it asks the database server for its timezone. Furthermore, this timezone is then used to translate between Date and Timestamp values. The Java environment does not understand the timezone code "ROC" and falls back to GMT:
```
jshell> TimeZone tz = TimeZone.getTimeZone("ROC");
tz ==> sun.util.calendar.ZoneInfo[id="GMT",offset=0,dstS ... ansitions=0,lastRule=null]

jshell> tz.getOffset(java.time.Instant.now().toEpochMilli());
$5 ==> 0

jshell> tz.getDisplayName();
$6 ==> "Greenwich Mean Time"
```
There might be another issue lurking somewhere, but could you perhaps try to set the timezone of your ClickHouse server to Asia/Taipei and see what happens?

**Comment by enqueue** [comment]
no response
