### ISSUE TITLE
Support of *Merge functions

### ISSUE THREAD

**Issue by arruzk** [enqueue/metabase-clickhouse-driver#21]
Hi, as I understand currently it's not possible to use [**Merge** combinator](https://clickhouse.yandex/docs/en/query_language/agg_functions/combinators/#aggregate_functions_combinators_merge).

I have a table with AggregatingMergeTree engine and columns with types like AggregateFunction(count), AggregateFunction(uniq, String).
Metabase is trying to do ```count(distinct `test6_click_aggregated`.`userKey_hll`)``` instead of `uniqMerge(userKey_hll)` and it's not possible to write this function to the `Custom Expression` field.

It works in the SQL mode, but it would be nice to have this functions.

**Comment by enqueue** [comment]
Hi @arruzk I think this would be quite difficult, because a driver only translates between the generic Metabase expressions and the database implementation. Right now I am focusing on getting all the generic Metabase features to work without errors.

**Comment by junbeilee** [comment]
I meet this question as well，Metabase can't suppot AggregatingMergeTree, this is a big loss

**Comment by enqueue** [comment]
Sorry, but adding support for ClickHouse specific „technical“ custom expressions is not something we are considering. Our focus is on getting standard Metabase functionality work with ClickHouse. You could perhaps try and create a view that merges the state and then make the view accessible from Metabae.
