### ISSUE TITLE
No method in multimethod 'date-add' for dispatch value: :clickhouse

### ISSUE THREAD

**Issue by dzarlax** [enqueue/metabase-clickhouse-driver#22]
Hi,
Got such error  in Metabase 0.32.10 when trying to filter date.
`No method in multimethod 'date-add' for dispatch value: :clickhouse`

**Comment by silenzushka** [comment]
Same for me. Happens when trying to filter date field using **Previous** expression.
![image](https://user-images.githubusercontent.com/9478/62684759-0cc0b900-b9ca-11e9-9e2c-936e13f90264.png)
Matabase for Mac: v0.32.10
ClickHouse Driver: 0.3

**Comment by enqueue** [comment]
Hi guys, thanks for reporting this. Will try to reproduce and fix this issue.

**Comment by enqueue** [comment]
Please try with release 0.4. Have a nice Sunday! Best regards, enqueue

**Comment by silenzushka** [comment]
Thank you @enqueue. Works perfectly!

**Comment by dzarlax** [comment]
@enqueue Wonderful! Thanks!
