### ISSUE TITLE
Month is moved backward in new version of Metabase + latest driver.

### ISSUE THREAD

**Issue by dzarlax** [enqueue/metabase-clickhouse-driver#25]
In Driver 0.4 and Metabase 0.32.8 August is shown like July.

Take a look at it please.

In previous versions everything is OK.

**Comment by enqueue** [comment]
Hi @dzarlax sorry about that. Could you please add some more detail to your description? What does your data look like in native ClickHouse client? What is your query in Metabase? Which timezones do your servers run at? Do you have access to ClickHouse query log? Perhaps you can see the "bad" statement. Or is the statement correct and the month names are 1 off in the Metabase result table?

**Comment by dzarlax** [comment]
This was fixed indirectly.
