### ISSUE TITLE
Search with non-ASCII letters doesn't work

### ISSUE THREAD

**Issue by amoskaliov** [enqueue/metabase-clickhouse-driver#26]
I have a search field in Metabase. Values contain non-ASCII (cyrillic) letters. The look like `Я_1`, `Я_2` and so on. For example I type `Я` in search field and Metabase sends query to Clickhouse like this:
```sql
SELECT
	`db_name`.`table_name`.`route_name` AS `route_name_mb_alias`
FROM
	`db_name`.`table_name`
WHERE
	(lower(`db_name`.`table_name`.`route_name`) like 'я%')
```

And Clickhouse returns nothing because `lower` function doesn't affect non-ASCII letters. One should use `lowerUTF8` instead.

Is it possible to force using `lowerUTF8` function while searching?

**Comment by enqueue** [comment]
@amoskaliov thanks for your bug report, and also the SQL statement. We can try to call toLowerCaseUTF8. If I wanted to write a test case, could I use your example for finding Я_1 and Я_2 values by searching for Я? What is the lower-case variant of Я?

Note to self: `sql/query_processor.clj` function `like-clause`

**Comment by amoskaliov** [comment]
>If I wanted to write a test case, could I use your example for finding Я_1 and Я_2 values by searching for Я?

Exactly. You can search for Я (u+042F) or я (u+044F) (as Metabase converts Я to я in its query).

**Comment by enqueue** [comment]
Hi @amoskaliov I have adjusted the driver to call `lowerUTF8` instead of `lower`, thanks for the hint. I haven't tested auto-completion in the filter fields, but I hope that Metabase is using the same methods. Please try it out.

**Comment by amoskaliov** [comment]
Yes, it works now. Thank you! Can we expect new release soon?

**Comment by enqueue** [comment]
I just built a new jar and uploaded it as version 0.5. Have fun!

**Comment by enqueue** [comment]
Can we close the ticket?

**Comment by amoskaliov** [comment]
Yes. Sorry I haven't yet. Thanks for your help.
