### ISSUE TITLE
http read timeout 30

### ISSUE THREAD

**Issue by xqwbx163** [enqueue/metabase-clickhouse-driver#33]
Hello,

I'm getting http read timeout in 30 seconds. I've checked Clickhouse settings related to timeout which are default as 600 seconds. (receive_timeout and send_timeout options. By default it's 600 sec.)

`:params nil},
:cause
{:class ru.yandex.clickhouse.except.ClickHouseException,
:error "ClickHouse exception, code: 159, host: 192.16.0.25, port: 8123; Read timed out",
:cause {:class java.net.SocketTimeoutException, :error "Read timed out"}}}`

How can I increase http read timeout using metabase-clickhouse jdbc?

Thanks

**Comment by enqueue** [comment]
Hi @xqwbx163 , have you tried to set the corresponding setting in the connection dialog, e.g. like this?

![connsettings](https://user-images.githubusercontent.com/5407006/66307301-5a8f6a00-e904-11e9-9b04-12d36b0373d8.png)

You can find the JDBC connection properties [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java)

**Comment by enqueue** [comment]
No answer

**Comment by karlseguin** [comment]
For anyone who lands here, note that the suggested fix, to change the JDBC properties, is currently not valid, since the JDBC properties cannot be changed. See: https://github.com/enqueue/metabase-clickhouse-driver/issues/85
