### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by telltime** [enqueue/metabase-clickhouse-driver#34]
I found that when there were too many charts, there would be obvious Carton. Yes, it's obvious. This is not the case when you switch to MySQL data sources. I'm sure it has nothing to do with the amount of data and the network.

**Comment by enqueue** [comment]
Hi @telltime , sorry I do not understand the problem from your description. Could you please be a little bit more verbose? What are you trying to do, what is the expected behavior, what is the actual behavior? You might also want to consider adding a screenshot or two...

**Comment by telltime** [comment]
But I created a dashboard on the metabase, then put 6 charts, I can see that the dashboard will open very slowly, I am sure this may be a driver problem.

**Comment by enqueue** [comment]
OK, could you perhaps take a look at the SQL statements that are generated by the driver and see if there is any obvious error or performance issue with it? Perhaps run the statements using native clickhouse-client and see how long they take. Thank you! Have a great day!

**Comment by enqueue** [comment]
@telltime sorry, but without any further information we cannot start a detailled analysis. „The performance of the driver is bad“ is too vague a statement.
