### ISSUE TITLE
when i select date(2019-01-02) in metabase filter,i found that clickhouse will receive 2019-01-01

### ISSUE THREAD

**Issue by li-bit** [enqueue/metabase-clickhouse-driver#38]

**Comment by enqueue** [comment]
Hi @li-bit thank you very much for trying out the driver and reporting the issue 👍 To follow up and investigate on it I would need a little bit more detail. What does the query look like in the front end, and what is the resulting query? What is your time zone, what time zone does your Metabase installation live in and what time zone is configured for ClickHouse? What is the data type of the column you are querying?

Please also see the [troubleshooting guide](https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html) by Metabase.

**Comment by li-bit** [comment]
What does the query look like in the front end:
![image](https://user-images.githubusercontent.com/13388843/69020379-3ccb1f80-09ef-11ea-8cab-a57b6d24e4db.png)

What is your time zone, what time zone does your Metabase installation live in and what time zone is configured for ClickHouse
--all of these are Asia/Taipei

What is the data type of the column you are querying
--date

**Comment by m4ex** [comment]
Hi, we have same issue. 
![photo_2019-12-11_15-18-13](https://user-images.githubusercontent.com/12564907/70620999-9e1a9300-1c29-11ea-8fbf-0bc6c315399e.jpg)

**Comment by skaboy007** [comment]
Hi so after a few checks I understand that the native query date filter in dashboards and the regular query date filter are not the same and the native filter is off by one day.

**Comment by enqueue** [comment]
Hi @skaboy007 thank you very much for investing the time to analyze the issue further. It should help us to create a test case for the future.

Unfortunately, there were some larger changes in Metabase 0.34, and I will have to make the driver work again (see issue #43). I am sorry.

**Comment by skaboy007** [comment]
Don't be sorry your driver is amazing as is, it brings a lot of value to the table. I cannot contribute with code but I will be happy to assist in use-cases analysis. we got a relatively big Metabase with click house running in production. 

you can ping me for assistance if needed

**Comment by enqueue** [comment]
Thank you for your kind words. It's great to hear that the driver is actually used outside our company, too :smile: 

If you have a test or dev environment, feel free to try out 0.7 BETA release, see my latest comment in #43

**Comment by long2ice** [comment]
Hi,I test some cases,maybe then question is ``toDateTime()`` function.

First I test select ``toDateTime()`` without timezone,the result is error:
![image](https://user-images.githubusercontent.com/13377178/75642726-77dc2080-5c77-11ea-9385-0d9b70a24a66.png)

Then I test with timezone,and it's right:
![image](https://user-images.githubusercontent.com/13377178/75642758-97734900-5c77-11ea-9cbf-675338363ace.png)
When write question in metabase with clickhouse,it will use ``toDateTime`` without timezone and cause timezone error.

And ``select now()``:

![image](https://user-images.githubusercontent.com/13377178/75643047-a3abd600-5c78-11ea-9a6a-727bc387277a.png)


Hope to useful!

**Comment by enqueue** [comment]
I tried to reproduce the behaviour locally using Metabase 0.34.3 and Metabase ClickHouse driver 0.7.0

1. Set ClickHouse time zone to Asia/Taipei (via docker TZ environment variable)
![Screenshot_20200309_203542](https://user-images.githubusercontent.com/5407006/76250857-00168300-6281-11ea-9787-08bfbbb36c99.png)
2. Start Metabase with JVM option `-Duser.timezone=Asia/Taipei`
![Screenshot_20200309_203428](https://user-images.githubusercontent.com/5407006/76250838-f68d1b00-6280-11ea-8632-58770558ee77.png)
3. Start web browser with `TZ=Asia/Taipei firefox`
![Screenshot_20200309_203508](https://user-images.githubusercontent.com/5407006/76250891-0e649f00-6281-11ea-8b9d-63d1d6ccc6e1.png)
4. Run query: `select {{date}}, now(), timezone();`
![Screenshot_20200309_203352](https://user-images.githubusercontent.com/5407006/76250964-30f6b800-6281-11ea-8636-f99d1417add8.png)

I do not see any offset. What am I doing wrong?

**Comment by skaboy007** [comment]
if I'm not mistaken the moment we upgrade to 0.34.3 with driver 7.0 beta the issue was gone

**Comment by enqueue** [comment]
Hi @li-bit and @m4ex can you confirm? If the problem still exists please let me know how your setup differs from the one I outlined in the previous comment. Thank you!

**Comment by m4ex** [comment]
Hi, sorry for long delay. I have tested latest version v0.38.1 with latest clickhouse driver, everything works as expected. Problem was fixed. I think we can close this issue. Thank you.

**Comment by enqueue** [comment]
Thank you for the update, @m4ex - closing this one for now. Have fun with Metabase and ClicHouse!
