### ISSUE TITLE
Inconvertible types at date range filter

### ISSUE THREAD

**Issue by ruber0id** [enqueue/metabase-clickhouse-driver#39]
I have such error when try apply date range filter to **Date** type column. Are parameter values for date range shouldn't be at such format "yyyy-MM-dd" (without time)?

```
ClickHouse exception, code: 169, host: 127.0.0.1, port: 8123; Code: 169, e.displayText() = DB::Exception: Key expression contains comparison between inconvertible types: Date and String inside (date AS `adserver.stat.date`) >= '2019-10-27 00:00:00'
```

**Information about Metabase**
Version: 0.33.4
Server: Ubuntu 18.04

**Comment by enqueue** [comment]
Hi @ruber0id Thank you for reporting this issue 👍 The handling of date / datetime / timestamp fields is one of the challenges for this driver and Metabase itself, too. I hope I will be able to address this specific error soon. Sorry about this!
