### ISSUE TITLE
Docker installation do not work

### ISSUE THREAD

**Issue by HKFiliatix** [enqueue/metabase-clickhouse-driver#40]
* metabase/metabase-head:latest
no app folder in it, only bin and target
* metabase/metabase
no app/pplugins folder, clickhouse plugin one in this folder and there is no clickohouse in database type drop down

Which version of metabase is working with this tutorial?

**Comment by enqueue** [comment]
Hi @HKFiliatix I just updated the README for the Docker operations. I tested both methods successfully.
