### ISSUE TITLE
Native query Variables filde filter not working 

### ISSUE THREAD

**Issue by skaboy007** [enqueue/metabase-clickhouse-driver#42]
Good day, I tried to make an interactive filtrable dashboard form a native query, which I did succeed to create but with some issues 
Whenever I use the Variables field filter (that enables the user to fuzzy search values of the column) the result is coming in empty. I overcome this issue by using a number variable instead of the field filter. in the dashboard, I mapped the filter to be associated with the corresponding column in the table, yet in the query itself, I have to resort to using a manually typed value which is inconvenient for the end-user, and most likely not usable. I also mapped the column in the data model to an ENUM to associate each value to a human-readable name. but I'm losing that readability by using number variable

could you guy's help out, it's not a deal-breaker by you know I think its good to polish the product as Metabase+clickhous is amazing and blazing fast.

![image](https://user-images.githubusercontent.com/50078277/71327304-98695b00-250f-11ea-8cb0-2daf57bfa8d2.png)

**Comment by enqueue** [comment]
Hi @skaboy007 what is the data type of Game ID? Do you see any error messages in either Metabase or ClickHouse?

I just tried this and it works. What am I doing differently? See video (`interface_id` is a String data type):

![clickhouse_metabase_issue_42_2020-03-09 19-19](https://user-images.githubusercontent.com/5407006/76244929-4fd25b80-623b-11ea-946e-a11378dfaa1a.gif)

**Comment by skaboy007** [comment]
I did not check after the update, but I did now. Seems to e working perfectly 
So cheers M8.
