### ISSUE TITLE
two columns with same alias name

### ISSUE THREAD

**Issue by mkabilov** [enqueue/metabase-clickhouse-driver#5]
When using UI, Metabase can produce queries having two aggregates with the same aliases:
```SQL
SELECT 
  sum(`default`.`stats`.`clicks`) AS `sum`,
  sum(`default`.`stats`.`impressions`) AS `sum`
FROM `default`.`stats`
FORMAT TabSeparatedWithNamesAndTypes;
```

it's ok for PostgreSQL and for some other databases, but not ok for ClickHouse:
```
2019.04.01 13:32:45.843693 [ 42 ] {38d731ce-1536-4670-ba77-645c7c415f08} <Error> HTTPHandler: Code: 179, e.displayText() = DB::Exception: Different expressions with the same alias sum:
sum(impressions) AS sum
and
sum(clicks) AS sum
```

I guess driver should take that into account and probably add suffixes for the aliases having the same name

**Comment by mkabilov** [comment]
JFYI, Oracle doesn't let you use the same alias twice in a SQL query (e.g. no SELECT field AS x, other_field AS x) 
see https://github.com/metabase/metabase/issues/9117

I wonder if it's possible to reuse code from the oracle driver?

https://github.com/metabase/metabase/blob/master/modules/drivers/oracle/src/metabase/driver/oracle.clj#L159-L202

**Comment by enqueue** [comment]
Thanks for the hint. I will try to understand the Oracle driver code; perhaps we can adopt it for the ClickHouse driver. If I remember correctly the _field_ aliases are generated in a different way than the aliases for aggregate functions, but I will have to check.

See also metabase/metabase#6042 where a work-around using custom expression is explained for SQL server.

**Comment by enqueue** [comment]
Good news. The issue with colliding alias names for aggregations been fixed by the Metabase team in metabase/metabase#9767 (target release is 0.33).

See attached example screenshot

![sum_alias_example](https://user-images.githubusercontent.com/5407006/62833124-aa6def80-bc39-11e9-9220-4b777e008245.png)

It results in the following query (notice the _sum\_2_):

```
SELECT
  count(*) AS `count`,
  sum(`db`.`mytable`.`customerBillingPartnerID`) AS `sum`,
  sum(`db`.`mytable`.`incoming`) AS `sum_2`
FROM
  `db`.`mytable`

```
