### ISSUE TITLE
Filtering Dates with no Results

### ISSUE THREAD

**Issue by PauloHFM** [enqueue/metabase-clickhouse-driver#50]
Hello!
I'm Using Metabase v0.35.3 and Driver 0.7.1

I have a DATE column and have data on the table like this picture below:

![Screenshot from 2020-04-29 18-27-51](https://user-images.githubusercontent.com/38223133/80648884-5d3fe100-8a47-11ea-97cd-f520e928a2af.png)

When I filter like this, it doesn't  return values:

![Screenshot from 2020-04-29 18-28-09](https://user-images.githubusercontent.com/38223133/80648882-5c0eb400-8a47-11ea-8394-e4b0599b2bda.png)
The generated SQL query is like this:
```
SELECT *
FROM `client`.`aggregated_stock`
WHERE (`date` >= parseDateTimeBestEffort('2020-04-26 00:00:00.000Z')
   AND `date` < parseDateTimeBestEffort('2020-04-27 00:00:00.000Z'))
ORDER BY `date` DESC
LIMIT 1048576
```
0 Results!

This is really a bug, but I think its because of the parseDateTimeBestEffort() function and it turns into a TIMESTAMP and the column is DATE type. BUT the interval, like it's on the query should not to this.

Other filters like BETWEEN doesn't work either.
PREVIOUS,BEFORE,CURRENT, it works!
 
@enqueue , do you know whats happening?

**Comment by PauloHFM** [comment]
My solution for now:
I altered all the date columns on click house from Date to DateTime. And I changed on MetaBase metadata the formatting of the columns to show only Dates. That's my way around it today.

**Comment by enqueue** [comment]
Yes, it is a bug. There were some optimizations in Metabase 0.34 and above to reduce the number of explicit casts, because some DBMS could not optimize such queries. I will have to find the right place in the driver to differentiate between Date and DateTime.

**Comment by enqueue** [comment]
I think we might get away with it, because more recent ClickHouse server versions will happily process such a statement. Could you perhaps try and check it out? I just updated my server to 20.4.5.36 and did the following:

```
CREATE TABLE datesversusdatetimes
(
  `foo` Date, 
  `bar` DateTime
)
ENGINE = MergeTree
PARTITION BY foo
ORDER BY foo;
```

```
INSERT INTO datesversusdatetimes (foo, bar) VALUES
('2020-06-16', '2020-06-16 16:01:01');
```

```
SELECT
  foo,
  bar
FROM
  datesversusdatetimes
WHERE
  (foo >= parseDateTimeBestEffort('2020-06-16 00:00:00.000Z'))
AND
  (foo < parseDateTimeBestEffort('2020-06-17 00:00:00.000Z'))
ORDER BY foo DESC;
```

The result is:
```
┌────────foo─┬─────────────────bar─┐
│ 2020-06-16 │ 2020-06-16 16:01:01 │
└────────────┴─────────────────────┘

1 rows in set. Elapsed: 0.008 sec.
```
Or did you have a different use case in mind? If so, please explain.

**Comment by enqueue** [comment]
With the latest changes and newer ClickHouse versions this should no longer be an issue
