### ISSUE TITLE
Arithmetic functions with other types other than Int or Float

### ISSUE THREAD

**Issue by PauloHFM** [enqueue/metabase-clickhouse-driver#52]
Hello! We cannot make Arithmetic calculations on clickhouse work only for INT or FLOAT as they say here: https://clickhouse.tech/docs/en/sql-reference/functions/arithmetic-functions/

> "Arithmetic functions work for any pair of types from UInt8, UInt16, UInt32, UInt64, Int8, Int16, Int32, Int64, Float32, or Float64."

My error on Metabase says exactly that:

`ClickHouse exception, code: 43, host: ec2-54-158-250-11.compute-1.amazonaws.com, port: 8123; Code: 43, e.displayText() = DB::Exception: Illegal types Float64 and Decimal(38, 2) of arguments of function divide (version 20.3.5.21 (official build)) `

So, on the driver we would cast the column to Float, right?

What do you think @enqueue ?

**Comment by enqueue** [comment]
Yes, we _used_ to have some code in there that did exactly that, i.e. cast any Decimal to a Float64. However, I dropped it during the latest release because the arithmetic functions changed. Let me see if we have to re-introduce the casting.

**Comment by enqueue** [comment]
Please try again using driver version 0.7.2

**Comment by PauloHFM** [comment]
Sorry for the late announcement, but.... it's FIXED! thx @enqueue

**Comment by enqueue** [comment]
Thanks for checking, @PauloHFM
