### ISSUE TITLE
Eror build driver not find  ru.yandex.clickhouse:clickhouse-jdbc:jar:0.2.4-enqueue 

### ISSUE THREAD

**Issue by sugengsuprayogi** [enqueue/metabase-clickhouse-driver#57]
When i build driver, i got error
`
Could not find artifact ru.yandex.clickhouse:clickhouse-jdbc:jar:0.2.4-enqueue in central (https://repo1.maven.org/maven2/)
Could not find artifact ru.yandex.clickhouse:clickhouse-jdbc:jar:0.2.4-enqueue in clojars (https://repo.clojars.org/)
`
Where is the artifact?

Thanks

**Comment by enqueue** [comment]
Thank you for your interest in building the driver! Please feed back any improvements or bug fixes you make via PR.

Please see the README:

> Unfortunately, newer versions require a JDBC driver that includes a couple of patches which have not been accepted upstream, yet (see [PR 418](https://github.com/ClickHouse/clickhouse-jdbc/pull/418)). I hope that we will soon be able to release another version which can then use an official JDBC driver again.

So this is what you would have to do

* Please checkout [my PR branch](https://github.com/enqueue/clickhouse-jdbc/tree/jdbc_4.2)
* Change `pom.xml` version number from 0.2.4 to 0.2.4-enqueue
* Run `mvn clean ... install`, this should make the artifact available in your local Maven repository

If you have any questions please let me know. Have a good day!

**Comment by sugengsuprayogi** [comment]
Thanks @enqueue
