### ISSUE TITLE
Cannot connect ClickHouse with Metabase 0.37

### ISSUE THREAD

**Issue by DaiZack** [enqueue/metabase-clickhouse-driver#58]
Cannot connect clickhoust with metabase 3.7

I use the docker and java to run the driver with the latest metabase, it cannot connect to clickhouse

But when I download the jar of metabase 3.5.7 it works well

**Comment by enqueue** [comment]
Hi @DaiZack I will try and update the driver before christmas 🎁🎅

**Comment by enqueue** [comment]
Hi @DaiZack  please try out the new release 0.7.3. I compiled it against 0.37.3 and am running it on our development server now. There are still some broken tests though. For 0.38 there is already new trouble on the horizon, concerning some casting of temporal strings. Please also make sure to use a pretty up-to-date ClickHouse server version. Please report back if this version works for you or if you have any issues. Thank you!

**Comment by nogara** [comment]
I tried the release 0.7.3 and it worked as well on the docker image `metabase/metabase:v0.37.4`

**Comment by enqueue** [comment]
Thanks for confirming, @nogara
