### ISSUE TITLE
Filter on IPv4 column

### ISSUE THREAD

**Issue by ppatrzyk** [enqueue/metabase-clickhouse-driver#69]
## My stack:

- ClickHouse server version 21.4.6 revision 54447.
- Metabase 0.39.1
- Clickouse plugin 0.7.5

## Problem description

In metabase: Ask question -> Custom question -> Filter -> ClientHost is some_ip

It's not possible to add a filter on column that is of type `IPv4`, it returns an error:

```
ClickHouse exception, code: 53, host: <HIDDEN>, port: 8123; Code: 53, e.displayText() = DB::Exception: Cannot convert string 10.0.1.23 to type IPv4: while executing 'FUNCTION notEquals(ClientHost : 0, '10.0.1.23' : 1) -> notEquals(ClientHost, '10.0.1.23') UInt8 : 3' (version 21.4.6.55 (official build)) 
```

Part of relevant table definition:

```
CREATE TABLE IF NOT EXISTS mydb.mytable (
    ClientHost IPv4,
)
```

Normally I query this via client with `where ClientHost = toIPv4('10.0.1.23')`

**Comment by enqueue** [comment]
Sorry about this. Do you have a good suggestion how to map the data type, @ppatrzyk ?

**Comment by ppatrzyk** [comment]
I updated the driver to new release and everything works fine, thanks for the fix!
