### ISSUE TITLE
Connection inside docker network

### ISSUE THREAD

**Issue by davidpham87** [enqueue/metabase-clickhouse-driver#73]
Hello,

I am trying to use metabase and clickhouse with the metabase-clickhouse-driver, however, I can't manage to connect to the clickhouse database when using a bridge network. The metabase container manage to communicate with the clickhouse container with `ping -c 1 name_clickhouse_container:5432`, and when I use `--network host`  metabase also manage to connect with host `localhost`, but when I am trying to set `name_clickhouse_container` as host inside metabase, ther error message says it is missing the port.

Would you know where the issue might reside?

Best regards,
David

I am trying to use this project: https://github.com/plausible/hosting with the docker instruction

```shell
docker run -d -p 3000:3000 \
-v ~/metabase-data:/metabase-data \
-net hosting_default \
-e "MB_DB_FILE=/metabase-data/metabase.db" \
--name metabase metabase/metabase
```
[please adapt the docker call in order to add the clickhouse driver].

**Comment by enqueue** [comment]
Sorry, but the driver does not interfere with any networking, and I do not know enough about Docker networking to help you
