### ISSUE TITLE
Send connection params to enable experimental features in clickhouse

### ISSUE THREAD

**Issue by vigneshnallamad** [enqueue/metabase-clickhouse-driver#74]
While adding clickhouse database connection, custom query parameters should be sent to enable experimental features. Sample connection string is pasted below.

clickhouse+native://warehouse.bookr.inc/bookr_dp?allow_experimental_window_functions=1

**Comment by enqueue** [comment]
This particular setting is no longer needed with newer ClickHouse versions (see ClickHouse/ClickHouse#26396).

However, if you ever need to set a different option, please use the field called "Additional JDBC connection string options" in the database administration screen. In my example I set the `client_name` property to the value "otters_rock".

![otters_rock_1](https://user-images.githubusercontent.com/5407006/144714710-8efb9291-8b83-49fb-9640-caaf32a80ebc.png)

The JDBC driver will pick up this property and use it for its queries. The String is logged in my database log:

```
2021.12.04 15:11:09.914639 [ 16045 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: [::1]:45000, User-Agent: otters_rock, Length: 209, Content Type: text/plain; charset=UTF-8, Transfer Encoding: identity, X-Forwarded-For: (none)
```
