### ISSUE TITLE
Run undockerized 

### ISSUE THREAD

**Issue by guidogabriel** [enqueue/metabase-clickhouse-driver#8]
Hi,
Is the anyway to use metabase-clickhouse in an undockerized metabase?

**Comment by enqueue** [comment]
Thanks for your interest in this project. I recently updated the [Readme](https://wiki.riege.de/display/POGO/Installed+Scope+Servers+body) with a section on how to test the driver using the official jar file. If you think the instructions should be improved, please create a PR. Basically, you'll just have to

1. Download a fairly recent MetaBase binary release (jar file) from the [MetaBase distribution page](https://metabase.com/start/jar.html).
2. Download the ClickHouse driver jar from this repository's "Releases" page
3. Create a directory and copy the `metabase.jar` to it.
4. In that directory create a sub-directory called `plugins`.
5. Copy the ClickHouse driver jar to the `plugins` directory.
6. Make sure you are the in the directory where your `metabase.jar` lives.
7. Run `MB_PLUGINS_DIR=./plugins; java -jar metabase.jar`.

Please let me know if you encounter any issues.

**Comment by guidogabriel** [comment]
First of all, thank you for reply.
I did it all this things but i still dont get to quering a csv endpoint.
Do i have to create a Database in metabase using Database type "ClickHouse"? Whats the parameters to connect? 
Do i have to install ClickHouse Database?
I just wanna consuming a csv like this:
SELECT 
    * 
FROM url(
    'https://raw.githubusercontent.com/oncletom/coursera-ml/master/week-1/people-example.csv',
    CSVWithNames,
    'firstname String, lastname String, country String, age UInt32'
)

**Comment by enqueue** [comment]
This project is about connecting MetaBase with a ClickHouse database.

I noticed that @AlexeyKupershtokh has used a ClickHouse database for proxying in metabase/metabase#4831, but If you only want to consume CSV and have no other use cases for ClickHouse database, there are probably easier ways to make the data accessible via MetaBase.  E.g. use PostgreSQL foreign data wrapper for CSV.

If you still want to use a ClickHouse database, you'll have to install the database, and follow the instructions I posted above. You can then set up your ClickHouse database as a backend in your MetaBase application. If you encounter any issues with this driver, please let us know.
