### ISSUE TITLE
ClickHouse exception, message: Error parsing 'true' as java.lang.Integer; For input string: "true"

### ISSUE THREAD

**Issue by Firm** [enqueue/metabase-clickhouse-driver#88]
Running query against table at clickhouse db ends with error.

Query: `select * from hits_v1 where product = 'analytics'`
Metabase error: `ClickHouse exception, message: Error parsing 'true' as java.lang.Integer; For input string: "true"`

The same query with clickchouse-client works fine when executed directly to clickhouse.

Metabase version: 0.42.4
ClickHouse driver version: 0.8.1
ClickHouse version: 22.1.3.7

Upd: `select count(*) from hits_v1 where product = 'analytics'` works fine in Metabase.

**Comment by mlazowik** [comment]
clickhouse supports `Bool` (stored as `UInt8`) since end of 2021: https://github.com/ClickHouse/ClickHouse/pull/31072

this driver does not yet: https://github.com/enqueue/metabase-clickhouse-driver/blob/cda0e7b01e38a1bec38c91e03799c06170fc69f7/src/metabase/driver/clickhouse.clj#L190

**Comment by fermuch** [comment]
Hello. Has there been any progress on this?

**Comment by Roman2nc** [comment]
hello, I am also requesting this correction. Thank you

**Comment by kingbabingge** [comment]
hello，I have the same problem too。

**Comment by slvrtrn** [comment]
Should be fixed in the upcoming 0.9.0 release.

**Comment by slvrtrn** [comment]
Let's keep it open until we publish the actual jar.

**Comment by stbeckers** [comment]
@slvrtrn thanks for fixing the boolean error. Do you already have a timeline when the 0.9.0 release is planned as we need it for one of our projects? 🙂

**Comment by slvrtrn** [comment]
@stbeckers [0.9.0](https://github.com/enqueue/metabase-clickhouse-driver/releases/tag/0.9.0) is out. Booleans should be fixed there. Please do not hesitate to open a new issue in case of any new findings.
