### ISSUE TITLE
Update JDBC Driver

### ISSUE THREAD

**Issue by jovezhong** [enqueue/metabase-clickhouse-driver#90]
As stated in https://github.com/ClickHouse/clickhouse-jdbc

> Maven groupId ru.yandex.clickhouse and legacy JDBC driver ru.yandex.clickhouse.ClickHouseDriver are deprecated.
> 
> Please use new groupId com.clickhouse and driver com.clickhouse.jdbc.ClickHouseDriver instead. It's highly recommended to upgrade to 0.3.2+ and start to integrate the new JDBC driver for improved performance and stability.

It'll be great if this driver can switch to the new JDBC driver. The code change should be small. Thanks.

**Comment by enqueue** [comment]
I would love to upgrade this driver, unfortunately, the JDBC driver is not compatible due to changes in Metadata. I will have to make adjustments for it.

**Comment by FesonX** [comment]
> I would love to upgrade this driver, unfortunately, the JDBC driver is not compatible due to changes in Metadata. I will have to make adjustments for it.

Any detail descriptions of incompatible changes in Metabase?
