### ISSUE TITLE
jdbc driver update

### ISSUE THREAD

**Issue by Brejneff** [enqueue/metabase-clickhouse-driver#92]
Hey folks!

What do you think about updating clickhouse jdbc driver used inside?
As far as I know in the latest version of metabase-clickhouse-driver the version `0.3.1` of the jdbc driver is used which was released in April 2021.
The latest official release is [v0.3.2-patch9](https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-patch9)

I'm asking this because we have a problem case.
We've created a field with type of `Map(LowCardinality(String), String)` and it causeв a problem in metabase: 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1566044/168095762-e64a27ac-fadb-4a82-a958-da7681b87516.png">

I've researched a bit and found out that this problem was fixed later in the jdbc driver: 
https://github.com/ClickHouse/clickhouse-jdbc/issues/730

Thanks

**Comment by enqueue** [comment]
Yes, it would be cool. Duplicate #90

**Comment by slvrtrn** [comment]
also related to #98
