### ISSUE TITLE
Getting only partial data from clickhouse

### ISSUE THREAD

**Issue by Jishnu-Prakash-K** [enqueue/metabase-clickhouse-driver#93]
When doing a simple select sum() query, I can see only 1/3rd the actual data visible in metabase. When I try from superset or query  directly using clickhouse client I'm getting the whole result. Could someone help me look into this, I tried the following versions

I can see that both the request, from superset and metabase, are going to same client.

1. Metabase : v0.42.4 Clickhouse driver : v0.8.1
2. Metabase : v0.41.2 Clickhouse driver : v0.8.0
3. Metabase : v.0.38.1 Clickhouse driver: v0.7.5

**Comment by enqueue** [comment]
Hi @Jishnu-Prakash-K Are you using the Metabase sum function in query builder or are you using an SQL query? If you are using the Metabase sum function, do you see anything interesting when converting this question to SQL?

**Comment by enqueue** [comment]
no further info
