### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by aleksandr-melnik1** [enqueue/metabase-clickhouse-driver#94]
i have problem with ssl:

PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

but metabase started with keystor java, system and java keystore have this certificate.
I can not specify the path to the certificate in the plugin.

**Comment by egorperesada** [comment]
Have the same issue, where can we put certificate if we can specify path to it

**Comment by enqueue** [comment]
Do you know the corresponding option in the JDBC driver?

**Comment by aleksandr-melnik1** [comment]
Could you show where and what options need to be added?

**Comment by smarkov92** [comment]
The parameter is called sslrootcert. Connection example
"jdbc:clickhouse://%s:8443/%s?ssl=1&sslmode=strict&sslrootcert=%s"

**Comment by enqueue** [comment]
probably related to #85

**Comment by slvrtrn** [comment]
We just released [0.8.3](https://github.com/enqueue/metabase-clickhouse-driver/releases/tag/0.8.3), which should bring back "additional JDBC connection string options".

Please try specifying additional JDBC connection string options (something like `sslrootcert=/path/to/CA.crt` as was suggested by @smarkov92) 

That should be available under the "advanced options":

![image](https://user-images.githubusercontent.com/3175289/205118056-b3657fa2-32eb-40e2-a419-e92f28a94184.png)

Please feel free to re-open the issue if it does not work for you.
