### ISSUE TITLE
feature request: support ssh tunnel

### ISSUE THREAD

**Issue by sixwaaaay** [enqueue/metabase-clickhouse-driver#99]
ssh tunnel for internal clickhouse server access

**Comment by slvrtrn** [comment]
Looking into it. For some reason, this setting disappeared some time ago despite having 

```yaml
connection-properties-include-tunnel-config: true
```

in the plugin manifesto.

**Comment by prakhar-goel** [comment]
In the meantime, you can setup local SSH tunnel.

So just run this on terminal:
ssh username@56.73.82.67  -N -f -L 8123:49.23.78.45:8123

56.73.82.67 - bastion server address
49.23.78.45 - Database server address (can be 127.0.0.1 if DB running directly on remote server).

This will setup a tunnel via server 56.73.82.67 and open Database running on 49.23.78.45:8123 and forward it to local laptop’s port 8123.

**Comment by slvrtrn** [comment]
Should be added in 0.9.1

**Comment by slvrtrn** [comment]
@sixwaaaay @prakhar-goel [0.9.1](https://github.com/enqueue/metabase-clickhouse-driver/releases/tag/0.9.1) is out, and it adds the SSH tunnel setting.
